baseurl = "https://www.doorwaysmagazine.com/"
languageCode = "en-us"
title = "Doorways Magazine"
[permalinks]
  post = "/:slug/"
  blog = "/:slug/"
  pages = "/:slug/"
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
